
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { databaseConfig } from '@/config/database';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  databaseConfig.supabaseUrl, 
  databaseConfig.supabaseAnonKey
);

// Log current configuration for debugging
console.log('🔧 Supabase client initialized:', {
  environment: databaseConfig.environment,
  url: databaseConfig.supabaseUrl.substring(0, 30) + '...',
  timestamp: new Date().toISOString()
});
