// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubsextjrmofwzvhvatcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVic2V4dGpybW9md3p2aHZhdGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzY5NjQsImV4cCI6MjA1NzgxMjk2NH0.bD3aCP9PATqXjXM6-Pwv1OpYRkPrAP73-UKffD6Kzjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);